# Site settings
author: Alethea Cary
title: My First Flatiron Project
header-img: img/home-bg.png
email: aletheacary@gmail.com
copyright_name: Alethea Cary
description: > # this means to ignore newlines until "baseurl:"
  Exploring a Basic User-Interface and Stocks
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  TrueC-D

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
